Repository jenkinsci/jenkinsfile-runner, pull requests merged in 2019-11, with the labels that each got.

#221 Fix grammar in README.md and DEVELOPER.md
  DEVELOPER.md
  README.md
Labels: documentation, hacktoberfest

#207 Add an interactive CLI mode (--cli argument)
  DOCKER.md
  README.md
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/App.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/CLILauncher.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsfileRunnerLauncher.java
Labels: needs-manual-testing

#217 Jenkinsfile: Optimize the build stage by using the Pipeline Library
  Jenkinsfile
Labels: chore, hacktoberfest

#198 Include the Plugin Installation Manager Tool into the Vanilla base image
  Dockerfile
  README.md
Labels: enhancement, hacktoberfest
