Repository jenkinsci/jenkinsfile-runner, pull requests merged in 2019-10, with the labels that each got.

#162 Add a link to the Jenkinsfile Runner presentation to README
  README.md
Labels: documentation

#168 Update the plugin Bill of Materials to version 3 for 2.176.x
  pom.xml
Labels: dependencies

#173 Add hyperlinks to the badges in README
  README.md
Labels: documentation, hacktoberfest

#154 Remove the Pipeline Step API test dependency
  payload-dependencies/pom.xml
  pom.xml
Labels: dependencies

#176 README: Reference GitHub issues as an alternate task tracker
  README.md
Labels: documentation

#187 #185 - Manage Vanilla package jenkins.war and plugins through a Maven module to prevent startup failures
  .gitignore
  DEVELOPER.md
  Dockerfile
  Dockerfile-dev
  demo/declarative-pipeline/Jenkinsfile
  plugins.txt
  pom.xml
  setup/pom.xml
  vanilla-package/pom.xml
Labels: bug, hacktoberfest

#183 #179 - Add '--help' CLI argument which prints help
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
Labels: enhancement, hacktoberfest

#182 #180 - Modify -v/--version flag to display the version + Use `-jv/--jenkinsVersion` for the former behavior
  README.md
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
Labels: breaking, enhancement, hacktoberfest

#194 Jenkinsfile: Increase the build timeout to 60min
  Jenkinsfile
Labels: chore

#184 #171 - Package Jenkinsfile Runner as a single JAR file with bundled dependencies + Include SSHD Module to the bundle to fix warning by the Git Server Plugin (Pipeline: Global CPS Library Dependency)
  app/pom.xml
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
  setup/pom.xml
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsfileRunnerLauncher.java
Labels: enhancement, hacktoberfest

#195 Disable Docker image deployment from ci.jenkins.io due to the unstable CI
  Jenkinsfile
Labels: hacktoberfest, internal

#200 Add Pipeline Utility Steps to the Vanilla Package
  demo/pipeline-utility-steps/Jenkinsfile
  demo/pipeline-utility-steps/README.md
  pom.xml
  vanilla-package/pom.xml
Labels: enhancement, hacktoberfest

#202 README: Remove the duplicated "Build" section, improve the quickstart rendering
  README.md
Labels: documentation, hacktoberfest

#205 Include Jenkins Configuration as Code plugin into the Vanilla Package (fixes #197)
  DOCKER.md
  Dockerfile
  Dockerfile-dev
  demo/casc/Jenkinsfile
  demo/casc/README.md
  demo/casc/config/jenkins.yaml
  pom.xml
  vanilla-package/pom.xml
Labels: enhancement, hacktoberfest

#206 Add Windows Dockerfile for jenkinsfile-runner
  Dockerfile-windows
  jenkinsfile-runner-launcher.ps1
Labels: enhancement, hacktoberfest

#203 Add `--job-name`, `--build-number` and `--cause` options
  README.md
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
  payload/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsfileRunnerCause.java
  payload/src/main/java/io/jenkins/jenkinsfile/runner/Runner.java
Labels: enhancement

#208 Add check of Minimum supported Jenkins version on startup
  bootstrap/pom.xml
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
Labels: enhancement, hacktoberfest

#215 Describe the vanilla image in the documentation, update Docker packaging guidelines
  README.md
Labels: documentation, hacktoberfest

#218 Add Git to the Vanilla image + add Maven demo
  demo/git-maven/Dockerfile
  demo/git-maven/Jenkinsfile
  demo/git-maven/jenkins.yaml
  demo/pipeline-library/README.md
  vanilla-package/pom.xml
Labels: dependencies, documentation

#219 Add a demo for the Pipeline library + Modify the development image to use the launcher entrypoint
  Dockerfile-dev
  demo/pipeline-library/Jenkinsfile
  demo/pipeline-library/README.md
  demo/pipeline-library/jenkins.yaml
Labels: chore, demo, documentation, hacktoberfest

#220 Add a Contributors badge
  README.md
Labels: documentation, hacktoberfest
