Repository jenkinsci/jenkinsfile-runner, pull requests merged in 2020-04, with the labels that each got.

#252 Add mirror option to speed the download
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
Labels: enhancement

#177 Update to the Jenkins 2.222.1 LTS baseline + use Jenkins Core BOM file as a dependency source + update dependencies
  pom.xml
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
  tests/test_resources/cwp-produced-images/config/packager-config-jdk11-more-specific.yml
  tests/test_resources/cwp-produced-images/config/packager-config-jdk11.yml
  tests/test_resources/cwp-produced-images/config/packager-config.yml
  tests/test_resources/negative-scenarios/config/packager-config-plugin-collision.yml
  tests/test_resources/negative-scenarios/config/packager-config-valid.yml
  vanilla-package/pom.xml
Labels: dependencies, hacktoberfest

#262 Add a Jenkinsfile Runner demo recording to README
  README.md
  demo/cwp/README.md
  demo/cwp/recording.gif
  demo/cwp/recording.yml
Labels: documentation

#263 Document how to run the JCasC demo locally with Vanilla packages
  demo/casc/README.md
Labels: documentation

#268 Add CODEOWNERS to automate review requests
  .github/CODEOWNERS
Labels: chore

#273 Revert "Bump version-number from 1.6 to 1.7"
  bootstrap/pom.xml
Labels: skip-changelog
