Repository jenkinsci/jenkinsfile-runner, pull requests merged in 2020-09, with the labels that each got.

#364 WorkflowJob.resumeBlocked = true
  payload/src/main/java/io/jenkins/jenkinsfile/runner/Runner.java
Labels: enhancement

#365 Update the Jenkins core from 2.246 to 2.249.1
  pom.xml
Labels: dependencies

#366 Update Plugin Installation Manager in Docker images from 0.1-alpha-10 to 2.0.1
  packaging/docker/unix/adoptopenjdk-11-hotspot/Dockerfile
  packaging/docker/unix/adoptopenjdk-11-jre-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-hotspot/Dockerfile
Labels: dependencies

#369 Make sure to pass an absolute directory for JENKINS_HOME
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
Labels: bug

#368 Allow not specifying any plugin file
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
Labels: enhancement
