Repository jenkinsci/jenkinsfile-runner, pull requests merged in 2020-10, with the labels that each got.

#370 Add a withHooks flag to provide a hook directory
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsEmbedder.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
Labels: enhancement

#378 Cleanup "Hudson" references in the Jenkinsfile Runner codebase
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsEmbedder.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/util/JenkinsHomeLoader.java
Labels: internal

#382 fixed spotbugs -> [ERROR] Format string should use %n rather than \n
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
Labels: bug

#381 ChangeLogParser - Use current directory when no directory is explicitly defined
  payload/src/main/java/io/jenkins/jenkinsfile/runner/FileSystemSCM.java
Labels: bug

#383 Enable SpotBugs reporting during the build
  Jenkinsfile
Labels: internal

#386 Use adoc code listing instead of md style
  docs/developer/CLASSLOADING.adoc
  docs/developer/DEBUG.adoc
  docs/using/EXTENDING_DOCKER.adoc
  packaging/docker/README.adoc
Labels: documentation

#391 Add Code Coverage Publishing to the build pipeline
  .gitignore
  Jenkinsfile
  pom.xml
Labels: internal

#393 Introduce Image Packs for Jenkinsfile Runner, with a first pack for Java builds with Apache Maven
  README.adoc
Labels: enhancement

#395 Fixing 'Packaging to Docker image' reference
  demo/casc/README.md
  demo/cwp/README.md
  demo/declarative-pipeline/README.md
  demo/git-maven/README.md
  demo/pipeline-as-yaml/README.md
  demo/pipeline-utility-steps/README.md
Labels: documentation

#387 Added github workflow for mirroring release artifacts
  .github/workflows/publish-release-artifact.yml
Labels: enhancement

#402 Parent Packaging POM: Allow overriding Jenkinsfile Runner version
  packaging-parent-pom/pom.xml
Labels: developer

#403 Update to the recent Plugin Bill of Materials + Cleanup dependencies which are now supplied by BOM
  packaging-parent-pom/pom.xml
  payload-dependencies/pom.xml
  pom.xml
  vanilla-package/pom.xml
Labels: dependencies

#404 Use project.version instead of project.parent version in Parent Packaging POM
  packaging-parent-pom/pom.xml
Labels: skip-changelog

#405 Add support for using custom logger configuration + Add Troubleshooting Guide
  README.adoc
  docs/using/TROUBLESHOOTING.adoc
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
Labels: documentation, enhancement

#407 Parent Packaging POM: Revert version customization support
  packaging-parent-pom/pom.xml
Labels: skip-changelog

#380 Initial native `checkout scm` support
  README.adoc
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
  docs/using/SCM.adoc
  payload-dependencies/pom.xml
  payload/src/main/java/io/jenkins/jenkinsfile/runner/Runner.java
  payload/src/main/java/io/jenkins/jenkinsfile/runner/SCMContainer.java
  tests/exclude-rsync.txt
  tests/pom.xml
  vanilla-package/pom.xml
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/SmokeTest.java
  vanilla-package/src/test/resources/io/jenkins/jenkinsfile/runner/vanilla/SmokeTest/checkoutSCM/Jenkinsfile
Labels: enhancement
