Repository jenkinsci/jenkinsfile-runner, pull requests merged in 2020-07, with the labels that each got.

#315 Update Jenkins Core to 2.235.2 and BOM to 2.235.x
  bootstrap/pom.xml
  pom.xml
  setup/pom.xml
Labels: dependencies

#319 Switch to GitHub-native Dependabot, ignore dependnecy versions coming from the Jenkins core
  .dependabot/config.yml
  .github/dependabot.yml
Labels: chore

#320 Restructure Docker image sources
  Jenkinsfile
  packaging/docker/build-mvncache/Dockerfile
  packaging/docker/unix/debian-jdk8/Dockerfile
  packaging/docker/unix/jenkinsfile-runner-launcher
  packaging/docker/windows/jenkinsfile-runner-launcher.ps1
  packaging/docker/windows/windowsservercore-jdk8/Dockerfile
Labels: chore, docker

#321 Move developer documentation to docs/developer + minor refresh
  CONTRIBUTING.md
  DOCKER.md
  README.md
  docs/developer/CLASSLOADING.md
  docs/developer/DEBUG.md
  docs/developer/README.md
  docs/developer/STRUCTURE.md
Labels: documentation

#322 Split DOCKER.md to user and developer documentation
  CONTRIBUTING.md
  DOCKER.md
  README.md
  docs/using/EXTENDING_DOCKER.md
  packaging/docker/unix/debian-jdk8/Dockerfile-dev
Labels: documentation

#323 Move old changelog to docs to avoid confusion
  docs/CHANGELOG.old.md
Labels: chore

#326 Changes mode of packaging/docker/unix/jenkinsfile-runner-launcher from 644 to 755
  packaging/docker/unix/jenkinsfile-runner-launcher
Labels: bug

#316 Add support for Pipeline as YAML plugin + Upgrade Declarative Pipeline from 1.6 to 1.7.1
  demo/pipeline-as-yaml/Jenkinsfile.yml
  demo/pipeline-as-yaml/README.md
  payload-dependencies/pom.xml
  payload/src/main/java/io/jenkins/jenkinsfile/runner/Runner.java
  pom.xml
  vanilla-package/pom.xml
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/SmokeTest.java
Labels: enhancement

#327 Update to Pipeline as YAML 1.0-rc-11 to reduce the dependency footprint
  pom.xml
Labels: dependencies

#328 Update to Pipeline as YAML 0.12-rc
  pom.xml
Labels: dependencies

#330 Fix Pipeline as YAML support + Optimize the Docker rebuild
  .dockerignore
  demo/pipeline-as-yaml/README.md
  packaging/docker/unix/debian-jdk8/Dockerfile
  packaging/docker/unix/jenkinsfile-runner-launcher
Labels: bug, chore

#331 Add recording of the Pipeline as YAML demo
  demo/pipeline-as-yaml/Jenkinsfile.yml
  demo/pipeline-as-yaml/README.md
  demo/pipeline-as-yaml/demo-recording.yml
Labels: documentation

#335 Update Dependabot config schema to v2
  .github/dependabot.yml
Labels: chore

#332 Add JDK 11 and JDK8/Alpine images, powered by AdoptOpenJDK
  packaging/docker/unix/11-jdk-hotspot/Dockerfile
  packaging/docker/unix/11-jre-alpine/Dockerfile
  packaging/docker/unix/8-jdk-alpine/Dockerfile
  packaging/docker/unix/jenkinsfile-runner-launcher
Labels: enhancement

#338 Switch the default Java 8 image to AdoptOpenJDK - Hotspot
  CONTRIBUTING.md
  Jenkinsfile
  packaging/docker/unix/11-jdk-hotspot/Dockerfile
  packaging/docker/unix/8-jdk-hotspot/Dockerfile
  packaging/docker/unix/8-jdk-hotspot/Dockerfile-dev
Labels: enhancement

#340 Fix wrong syntax in the documentation
  demo/pipeline-utility-steps/README.md
Labels: documentation

#339 Properly export the minimum supported Jenkins version
  app/pom.xml
  app/src/main/resources-filtered/jenkins.properties
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
Labels: bug

#341 Update documentation to reflect the new Docker packaging + Update the databound demo to the new Jenkins core and plugin versions
  Jenkinsfile
  README.md
  demo/databound/packager-config.yml
  docs/using/EXTENDING_DOCKER.md
  packaging/docker/README.md
  packaging/docker/unix/adoptopenjdk-11-hotspot/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-hotspot/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-hotspot/Dockerfile-dev
  packaging/docker/unix/adoptopnejdk-11-jre-alpine/Dockerfile
Labels: documentation

#342 Fix typo in the adoptopnejdk-11-jre-alpine directory name
  packaging/docker/unix/adoptopenjdk-11-jre-alpine/Dockerfile
Labels: skip-changelog

#348 Update the Custom WAR Packager demos to use the new plugins and the Jenkins core
  demo/cwp-jdk11/packager-config.yml
  demo/cwp/packager-config.yml
  demo/databound/packager-config.yml
Labels: demo, documentation

#349 Stop bundling plugin HPI files in Linux Docker images
  packaging/docker/unix/adoptopenjdk-11-hotspot/Dockerfile
  packaging/docker/unix/adoptopenjdk-11-jre-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-hotspot/Dockerfile
Labels: enhancement

#346 Exclude jenkins.war and executable-war.jar from Jenkinsfile Runner bundles
  app/pom.xml
  demo/cwp/packager-config.yml
  demo/databound/packager-config.yml
  pom.xml
  setup/pom.xml
Labels: bug
