Repository jenkinsci/jenkinsfile-runner, pull requests merged in 2020-11, with the labels that each got.

#411 Fix some spotbugs warnings
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/ClassLoaderBuilder.java
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Util.java
Labels: chore

#417 Resolved managed dependencies versioning
  app/pom.xml
  packaging-parent-pom/pom.xml
Labels: dependencies

#427 Clarify use-cases of the --war argument in CLI
  README.adoc
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
Labels: documentation

#430 Maven packaging Parent POM: Allow using custom version numbers in child packaging POMs + Allow setting a Jenkinsfile Runner version via `jfr.version` + Ensure that plugin dependencies are aligned with JFR requirements
  Jenkinsfile
  demo/cwp/packager-config.yml
  demo/databound/Jenkinsfile
  demo/databound/Makefile
  demo/databound/README.md
  demo/databound/packager-config.yml
  packaging-parent-pom/jfr-main-repo-marker.txt
  packaging-parent-pom/pom.xml
  packaging-parent-resources/pom.xml
  packaging-parent-resources/src/main/resources-filtered/jenkins.properties
  packaging-parent-resources/src/main/resources/assembly/zip.xml
  packaging/docker/unix/adoptopenjdk-11-hotspot/Dockerfile
  packaging/docker/unix/adoptopenjdk-11-jre-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-hotspot/Dockerfile
  payload-dependencies/pom.xml
  payload-dependencies/src/main/java/io/jenkins/jenkinsfile/runner/payloadDeps/PayloadDependencies.java
  payload/pom.xml
  pom.xml
  vanilla-package/jfr-main-repo-marker.txt
  vanilla-package/pom.xml
Labels: developer, internal

#431 Cleanup some SpotBugs warnings
  setup/src/main/java/io/jenkins/jenkinsfile/runner/CLILauncher.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsEmbedder.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
Labels: chore

#426 Update Jenkins core from 2.249.1 to 2.263.
  pom.xml
Labels: dependencies

#425 Update Jenkins Plugin Installation Manager tool from 2.0.1 to 2.1.3
  packaging/docker/unix/adoptopenjdk-11-hotspot/Dockerfile
  packaging/docker/unix/adoptopenjdk-11-jre-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-hotspot/Dockerfile
Labels: dependencies

#433 [Github-Actions] fixing depricated env setup
  .github/workflows/publish-release-artifact.yml
Labels: chore

#434 Revert the jfr.version support and minimun Jenkins core version
  Jenkinsfile
  demo/cwp/packager-config.yml
  packaging-parent-pom/pom.xml
  pom.xml
Labels: skip-changelog

#435 Update Plugin Installation Manager in Docker images to 2.2.0
  packaging/docker/unix/adoptopenjdk-11-hotspot/Dockerfile
  packaging/docker/unix/adoptopenjdk-11-jre-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-hotspot/Dockerfile
Labels: dependencies

#436 Update Docker builder to Maven 3.6.3, add batch mode flags
  packaging/docker/unix/adoptopenjdk-11-hotspot/Dockerfile
  packaging/docker/unix/adoptopenjdk-11-jre-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-alpine/Dockerfile
  packaging/docker/unix/adoptopenjdk-8-hotspot/Dockerfile
Labels: chore

#432 Switch Jenkinsfile Runner CLI from args4j to picocli
  bootstrap/pom.xml
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
  bootstrap/src/main/resources-filtered/jfr.properties
  bootstrap/src/test/java/io/jenkins/jenkinsfile/runner/bootstrap/BootstrapTest.java
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/JFRTestUtil.java
Labels: chore
