Repository jenkinsci/jenkinsfile-runner, pull requests merged in 2020-05, with the labels that each got.

#282 Update declarative Pipeline and Git/Maven demos to reflect the current state of the Vanilla package
  demo/declarative-pipeline/README.md
  demo/git-maven/Dockerfile
  demo/git-maven/README.md
  demo/git-maven/jenkins.yaml
Labels: demo

#281 [JENKINS-57441] - Fix warning about missing User config path on startup
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
Labels: bug

#284 Fix typo
  README.md
Labels: documentation

#283 Speedup vanilla package testing: .dockerignore and a development mode flag in tests
  .dockerignore
  tests/Makefile
  tests/README.md
  tests/tests-vanilla.sh
Labels: chore

#271 Update the plugin BOM to the latest version of 2.222.x
  pom.xml
Labels: dependencies

#285 Move simple integration tests from JFR Test Framework to JUnit + Disable broken Custom War Packager integration tests
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
  payload/src/main/java/io/jenkins/jenkinsfile/runner/Runner.java
  pom.xml
  tests/Makefile
  tests/test_resources/cwp-produced-images/test_databound/Jenkinsfile
  tests/test_resources/negative-scenarios/config/packager-config-valid.yml
  tests/test_resources/negative-scenarios/test_pipeline_execution_fails/Jenkinsfile
  tests/test_resources/negative-scenarios/test_pipeline_execution_fails_bad_syntax/Jenkinsfile
  tests/test_resources/negative-scenarios/test_pipeline_execution_hangs/Jenkinsfile
  tests/test_resources/negative-scenarios/test_pipeline_execution_is_unstable/Jenkinsfile
  tests/test_resources/vanilla-images/test_declarative_pipeline/Jenkinsfile
  tests/test_resources/vanilla-images/test_scripted_pipeline/Jenkinsfile
  tests/tests-cwp.sh
  tests/tests-negative-scenarios.sh
  tests/tests-vanilla.sh
  vanilla-package/pom.xml
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/JFRTestUtil.java
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/ParametersTest.java
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/SmokeTest.java
Labels: chore

#288 Add separate Dockerfile for Maven Cache
  src/docker-mvncache/Dockerfile
Labels: chore

#287 Fix the CI
  Dockerfile
  Jenkinsfile
  pom.xml
  vanilla-package/pom.xml
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/JFRTestUtil.java
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/ParametersTest.java
Labels: chore

#290 Add "All contributors" to the changelog template
  .github/release-drafter.yml
Labels: chore

#291 Fix the changelog badge
  README.md
Labels: documentation, skip-changelog

#289 Dockerfile: Use jenkins4eval/jenkinsfile-runner:build-mvncache when building images
  Dockerfile
  src/docker/build-mvncache/Dockerfile
Labels: chore

#292 Maven Cache: Prevent failures due to unit tests on the cache build
  src/docker/build-mvncache/Dockerfile
Labels: chore

#293 Vanilla tests: Increase timeout to two minutes
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/ParametersTest.java
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/SmokeTest.java
Labels: chore

#295 Ensure that Maven Cache performs the full build
  src/docker/build-mvncache/Dockerfile
Labels: chore

#294 Prevent PluginServletFilter warnings when running JFR as a standalone JAR
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
Labels: bug

#298 Replace jsr-305 annotations with SpotBugs ones
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
  payload/src/main/java/io/jenkins/jenkinsfile/runner/FileSystemSCM.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsEmbedder.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/WarExploder.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/util/HudsonHomeLoader.java
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/JFRTestUtil.java
Labels: chore

#267 Add compressed war option
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Util.java
Labels: enhancement
