Repository jenkinsci/jenkinsfile-runner, pull requests merged in 2021-06, with the labels that each got.

#511 Added a 'lint' command
  .gitignore
  README.adoc
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Bootstrap.java
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/JenkinsfileCommand.java
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/LintJenkinsfileCommand.java
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/PipelineLintOptions.java
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/PipelineOptions.java
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/PipelineRunOptions.java
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/RunJenkinsfileCommand.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/App.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsfileLinterLauncher.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsfileRunnerLauncher.java
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/JFRTestUtil.java
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/SmokeTest.java
Labels: enhancement

#517 Allow exposing HTTP and Agent connection ports via `--httpPort` and `--agentPort` options
  README.adoc
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/JenkinsLauncherOptions.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
Labels: enhancement

#516 Update Jenkins to 2.289.1, use the latest plugins BOM
  demo/cwp/packager-config.yml
  pom.xml
  setup/pom.xml
Labels: dependencies

#518 Update picocli from 4.5.2 to 4.6.1
  bootstrap/pom.xml
Labels: dependencies

#520 Allow running JFR tests with Jenkins UI
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/Util.java
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/JFRTestUtil.java
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/ParametersTest.java
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/SmokeTest.java
Labels: chore

#525 Publish incrementals
  .mvn/extensions.xml
  .mvn/maven.config
  Jenkinsfile
  app/pom.xml
  bootstrap/pom.xml
  packaging-parent-pom/pom.xml
  packaging-parent-resources/pom.xml
  packaging-slim-parent-pom/pom.xml
  payload-dependencies/pom.xml
  payload/pom.xml
  pom.xml
  setup/pom.xml
  tests/pom.xml
  vanilla-package/pom.xml
Labels: developer

#526 Removing JSR 250 `@PostConstruct`
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/JenkinsLauncherCommand.java
Labels: chore

#529 Force to PERFORMANCE_OPTIMIZED for Pipeline execution
  payload/src/main/java/io/jenkins/jenkinsfile/runner/Runner.java
Labels: bug
