Repository jenkinsci/jenkinsfile-runner, pull requests merged in 2023-08, with the labels that each got.

#696 Update to Jenkins LTS version 2.375
  bootstrap/pom.xml
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/JenkinsLauncherCommand.java
  packaging-parent-pom/pom.xml
  payload-dependencies/pom.xml
  payload/src/main/java/io/jenkins/jenkinsfile/runner/PipelineAsYAMLDefinitionProvider.java
  payload/src/main/java/io/jenkins/jenkinsfile/runner/SetJenkinsfileLocation.java
  pom.xml
  setup/pom.xml
  setup/src/main/java/io/jenkins/jenkinsfile/runner/CLILauncher.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsLauncher.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsfileLinterLauncher.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/JenkinsfileRunnerLauncher.java
  setup/src/main/java/io/jenkins/jenkinsfile/runner/NoListenerConfiguration.java
  vanilla-package/pom.xml
  vanilla-package/src/test/java/io/jenkins/jenkinsfile/runner/vanilla/SmokeTest.java
Labels: dependencies

#698 Add --write-log-init-timeout option to allow specifying a timeout to retry writing logs to stdout
  bootstrap/src/main/java/io/jenkins/jenkinsfile/runner/bootstrap/commands/PipelineRunOptions.java
  payload/src/main/java/io/jenkins/jenkinsfile/runner/Runner.java
Labels: enhancement

#682 Update the roadmap links in the document
  README.adoc
  ROADMAP.adoc
Labels: documentation

#700 Add GitHub Action for Release Drafter
  .github/workflows/release-drafter.yml
Labels: chore
